language: node_js
node_js:
  - "10"
script:
  - yarn lint
  - yarn test
cache:
  yarn: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master
